config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', path_names: { sign_in: '', sign_out: 'logout'}

  resources :products
  resources :categories
  resources :brands

  resources :quote_items, only: [:create, :edit, :update, :destroy]

  get 'quote', to: 'quotes#show', as: 'quote'
  get 'quote/edit', to: 'quotes#edit', as: 'edit_quote'
  patch 'quote', to: "quotes#update"
  get 'quotes/:id/send', to: 'quotes#send_my_quote', as: 'send_my_quote'

  root 'pages#home'

  get 'redirect', to: 'pages#redirect', as: 'redirect'

  get 'legal', to: 'pages#legal', as: 'legal'
  get 'privacy_policy', to: 'pages#policy', as:'policy'
  get 'cgu', to: 'pages#cgu', as: 'cgu'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :quote_items, dependent: :destroy
  has_many :products, through: :quote_items

  validates :phone, format: { with: /\A0[1-9]\d{8}\z/ , message: ": Le numéro de téléphone doit être français et valide, composé uniquement de  10 chiffres" }
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\.[^@\s]+\z/, message: "doit être de type exemple@email.fr" }


end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_or_create_quote, only: [:show, :edit, :update, :send_my_quote]

  def show
    @quote_items = @quote.quote_items.includes(product: [:category, :brand]).sort_by { |item|
      [item.product.category.name, item.product.brand.name]
    }
    @products = @quote.products
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      redirect_to quote_path
    else
      render :edit
    end
  end

  def send_my_quote
    QuotesMailer.send_quote(@quote).deliver_now!
    QuotesMailer.send_for_asker(@quote).deliver_now!
    redirect_to redirect_path
    new_quote = Quote.create!
    session[:quote_id] = new_quote.id
  end

  private

  def set_or_create_quote
    @quote = Quote.find_by(id: session[:quote_id]) || Quote.create!
    session[:quote_id] = @quote.id
  end

  def quote_params
    params.require(:quote).permit(:first_name, :last_name, :phone, :email, :address, :company)
  end

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form-quote.html.erb
<%= form_with(model: quote, local: true, method: :patch, class: 'form', id:'form') do |form| %>
  <div class="container">
    <div class="row w-75 mx-auto">

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :first_name, "Prénom" %>
          <%= form.text_field :first_name, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :last_name, "Nom" %>
          <%= form.text_field :last_name, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :company, "Société" %>
          <%= form.text_field :company, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :address, "Adresse" %>
          <%= form.text_field :address, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :phone, "Téléphone" %>
          <%= form.text_field :phone, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 d-flex justify-content-center align-items-center">
        <div class="my-3">
          <%= form.submit 'Mettre à jour', class: 'btn btn-primary' %>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/quotes/_params-quote.html.erb
<% if quote.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(quote.errors.count, "erreur") %> empêche(nt) ce devis d'être enregistré :</h2>

    <ul>
    <% quote.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: quote, local: false, method: :patch, class: 'form', id:'form') do |form| %>
  <div class="container">
    <div class="row w-75 mx-auto">

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :first_name, "Prénom", autofocus: true %>
          <%= form.text_field :first_name, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :last_name, "Nom" %>
          <%= form.text_field :last_name, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :company, "Société" %>
          <%= form.text_field :company, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :address, "Adresse" %>
          <%= form.text_field :address, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :phone, "Téléphone" %>
          <%= form.number_field :phone, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :email, "Email" %>
          <%= form.text_field :email, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 d-flex justify-content-center align-items-center">
        <div class="my-3">
          <%= form.submit 'Mettre à jour', class: 'btn btn-danger' %>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1 class="text-center my-5 text-danger">
  MODIFIER LE DEVIS
</h1>

<%= form_with(model: @quote, local: false, method: :patch, class: 'form', id:'form') do |form| %>
  <div class="container">
    <div class="row w-75 mx-auto">

      <% if @quote.errors.any? %>
        <div id="error_explanation" class="col-12 col-md-8">
          <p><%= pluralize(@quote.errors.count, "erreur") %> empêche(nt) ce devis d'être enregistré :</p>

          <ul>
            <% @quote.errors.full_messages.each do |message| %>
              <li class="text-danger"><%= message %></li>
            <% end %>
          </ul>
        </div>

      <% end %>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :first_name, "Prénom", autofocus: true %>
          <%= form.text_field :first_name, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :last_name, "Nom" %>
          <%= form.text_field :last_name, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :company, "Société" %>
          <%= form.text_field :company, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :address, "Adresse" %>
          <%= form.text_field :address, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :phone, "Téléphone" %>
          <%= form.number_field :phone, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <div class="my-3">
          <%= form.label :email, "Email" %>
          <%= form.text_field :email, class: 'form-control' %>
        </div>
      </div>

      <div class="col-12 d-flex justify-content-center align-items-center">
        <div class="my-3">
          <%= form.submit 'Mettre à jour', class: 'btn btn-danger' %>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/quotes/show.html.erb
<h1 class="text-center my-5 text-danger">
  MON DEVIS
</h1>

<%= render 'quotes/params-quote', quote: @quote %>

<% if @quote_items.any? %>
<div class="container">
  <div class="row">
    <div class="col-12">

      <table class="table table-primary table-striped table-hover table-bordered border-2">
        <thead class="table-secondary border-3">

          <td class="border-3">
            PRODUITS
          </td>
          <td class="border-3">
            VENDU PAR
          </td>
          <td class="border-3">
            QUANTITE
          </td>
        </thead>
        <% @quote_items.group_by { |item| item.product.category }.each do |category, items| %>
                <thead class="w-75 mx-auto">
                    <tr class="table-danger">
                        <td colspan="3">
                          <%= link_to category.name.upcase, category_path(category), class: "text-decoration-none text-dark" %>
                        </td>
                    </tr>
                </thead>
          <tbody>
            <% items.each do |item| %>
              <tr class="table-warning">

                <td>
                  <%= cl_image_tag item.product.photo.key, class: 'img-fluid shadow-lg', width: 48, alt: item.product.name %>

                  <%= link_to item.product.name, product_path(item.product), class: "text-decoration-none text-dark" %>
                </td>
                <td>
                  <%= item.product.box %>
                </td>

                <td>

                  <div class="row text-center align-items-center">

                    <div class="col-md-3 col-12">
                      <%= item.quantity %>
                    </div>

                    <div class="col-md-9 col-12">
                      <%= link_to '✏️', edit_quote_item_path(item), class: "btn btn-secondary" %>
                      <%= link_to '❌', quote_item_path(item), data: {turbo_method: :delete}, class: "btn btn-danger" %>
                    </div>
                  </div>
                </td>

              </tr>
            <% end %>
          </tbody>
        <% end %>
      </table>

      <div class="text-center">
        <%= link_to 'Ajouter un autre produit', products_path, class: "btn btn-secondary" %>
        <%= link_to 'ENVOYER LE DEVIS', send_my_quote_path(@quote), class: "btn btn-danger" %>
      </div>

    </div>
  </div>

</div>




<% else %>
  <p class="text-center my-5">
    Votre devis est vide pour le moment. Allez sur un produit pour l'ajouter à votre devis.
  </p>

  <div class="text-center">
    <%= link_to 'Ajouter un autre produit', products_path, class: "btn btn-secondary" %>
  </div>
<% end %>