config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', path_names: { sign_in: '', sign_out: 'logout'}

  resources :products
  resources :categories
  resources :brands

  resources :quote_items, only: [:create, :edit, :update, :destroy]

  get 'quote', to: 'quotes#show', as: 'quote'
  get 'quote/edit', to: 'quotes#edit', as: 'edit_quote'
  patch 'quote', to: "quotes#update"
  get 'quotes/:id/send', to: 'quotes#send_my_quote', as: 'send_my_quote'

  root 'pages#home'

  get 'redirect', to: 'pages#redirect', as: 'redirect'

  get 'legal', to: 'pages#legal', as: 'legal'
  get 'privacy_policy', to: 'pages#policy', as:'policy'
  get 'cgu', to: 'pages#cgu', as: 'cgu'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
  belongs_to :category
  belongs_to :brand

  has_many :quote_items, dependent: :destroy
  has_many :quotes, through: :quote_items

  def self.ransackable_associations(auth_object = nil)
    %w[brand category]
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end

  def self.ransackable_scopes(auth_object = nil)
    %w[search_by_category_name]
  end

  def self.search_by_category_name(query)
    joins(:category).where("categories.name ILIKE ?", "%#{query}%")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_or_create_quote, only: [:show]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @products = if params[:q].present?
                  @q.result(distinct: true)

                else
                  Product.all.with_attached_photo
                end
  end

  def show
    @product = Product.find(params[:id])
    @quote_item = QuoteItem.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save!
      redirect_to product_path(@product)
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    if @product.save
      redirect_to product_path(@product)
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def set_or_create_quote
    @quote = Quote.find_by(id: session[:quote_id]) || Quote.create!
    session[:quote_id] = @quote.id
  end

  def product_params
    params.require(:product).permit(:name, :box, :link, :photo, :category_id, :brand_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@product) %>

app/views/products/edit.html.erb
<h1 class="my-5 text-center text-danger">MODIFIER CE PRODUIT</h1>

<%= form_with(model: @product, local: true, class: 'form') do |form| %>
  <div class="row w-75 mx-auto">
    <div class="form-group col-12 col-md-6 my-3">
      <%= form.label :name, "Nom du produit" %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>


    <div class="form-group col-12 col-md-6 my-3">
      <%= form.label :box, "Vendu par" %>
      <%= form.text_field :box, class: 'form-control' %>
    </div>

    <div class="form-group col-12 col-md-6 my-3">
      <%= form.label :category_id, "Catégorie" %>
      <%= form.collection_select :category_id, Category.order(:name), :id, :name, { prompt: "Sélectionner une catégorie" }, { class: 'form-select' } %>

    </div>

    <div class="form col-12 col-md-6 my-3">
      <%= form.label :brand_id, "Marque" %>
      <%= form.collection_select :brand_id, Brand.order(:name), :id, :name, { prompt: "Sélectionner une marque" }, { class: 'form-select' } %>
    </div>

    <div class="form-group col-12 col-md-6 my-3">
      <%= form.label :photo, "Photo" %>
      <%= form.file_field :photo, as: :file, class: "form-control" %>
    </div>

  </div>


  <div class="form-group text-center my-3">
    <%= form.submit 'METTRE A JOUR', class: 'btn btn-success' %>
  </div>

  <div class="text-center my-3">
  <%= link_to 'SUPPRIMER CE PRODUIT', product_path(@product), class:"btn btn-dark", data: {turbo_method: :delete} %>
</div>
<% end %>

app/views/products/index.html.erb
<h1 class="my-5 text-center text-danger">
  Tous nos produits
  <% if @q && @q.conditions.any? %>
    correspondant à "<%= @q.conditions.map(&:value).join(", ") %>"
  <% end %>
</h1>

<%= render 'layouts/index/all', q: @q, categories: @categories, brands: @brands, products: @products %>

app/views/products/new.html.erb
<h1 class="my-5 text-center text-danger">CREER UN PRODUIT</h1>

<%= form_with(model: @product, local: true, class: 'form') do |form| %>
  <div class="row w-75 mx-auto">

    <div class="form-group col-12 col-md-6 my-3">
      <%= form.label :name, "Nom du produit" %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>


    <div class="form-group col-12 col-md-6 my-3">
      <%= form.label :box, "Vendu par" %>
      <%= form.text_field :box, class: 'form-control' %>
    </div>

    <div class="form-group col-12 col-md-6 my-3">
      <%= form.label :category_id, "Catégorie" %>
      <%= form.collection_select :category_id, Category.order(:name), :id, :name, { prompt: "Sélectionner une catégorie" }, { class: 'form-select' } %>

    </div>

    <div class="form col-12 col-md-6 my-3">
      <%= form.label :brand_id, "Marque" %>
      <%= form.collection_select :brand_id, Brand.order(:name), :id, :name, { prompt: "Sélectionner une marque" }, { class: 'form-select' } %>
    </div>

    <div class="form-group col-12 col-md-6 my-3">
      <%= form.label :photo, "Photo" %>
      <%= form.file_field :photo, as: :file, class: "form-control" %>
    </div>


  </div>


  <div class="form-group text-center my-3">
    <%= form.submit 'AJOUTER LE PRODUIT', class: 'btn btn-success' %>
  </div>

<% end %>

app/views/products/show.html.erb
<div class="container mt-5">
  <div class="row">

    <div class="col-md-6 text-center">
      <%= cl_image_tag @product.photo.key, class: 'img-fluid rounded shadow-lg', alt: @product.name %>
    </div>

    <div class="col-md-6 text-center">
      <%= link_to 'MODIFIER ce Produit', edit_product_path(@product) if current_admin %>
      <h1 class="display-4 shadow-3 p-3"><%= @product.name %></h1>

      <table class="table table-warning table-bordered table-striped-columns">
        <thead>
          <tr class="">
            <td>
              Marque
            </td>
            <td>
              <%= @product.brand.name %>
            </td>
          </tr>
          <tr class="">
            <td>
              Rangé dans la catégorie
            </td>
            <td>
              <%= @product.category.name %>
            </td>
          </tr>
        </thead>



        <tr class="table-danger">
          <td>
            VENDU PAR
          </td>
          <td>
            <%= @product.box %>
          </td>
        </tr>




      </table>

        <% unless @quote.quote_items.exists?(product_id: @product.id) %>
          <div class="text-center">
            <%= form_with url: quote_items_path, method: :post do %>
              <%= hidden_field_tag :product_id, @product.id %>
              <%= submit_tag "AJOUTER AU DEVIS", class: "btn btn-danger" %>
            <% end %>
          </div>
        <% else %>
          <button class="btn btn-danger" disabled>Produit déjà ajouté</button>
        <% end %>


      <!-- Ajouter ici d'autres détails sur le produit si nécessaire -->
    </div>
  </div>
</div>