config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', path_names: { sign_in: '', sign_out: 'logout'}

  resources :products
  resources :categories
  resources :brands

  resources :quote_items, only: [:create, :edit, :update, :destroy]

  get 'quote', to: 'quotes#show', as: 'quote'
  get 'quote/edit', to: 'quotes#edit', as: 'edit_quote'
  patch 'quote', to: "quotes#update"
  get 'quotes/:id/send', to: 'quotes#send_my_quote', as: 'send_my_quote'

  root 'pages#home'

  get 'redirect', to: 'pages#redirect', as: 'redirect'

  get 'legal', to: 'pages#legal', as: 'legal'
  get 'privacy_policy', to: 'pages#policy', as:'policy'
  get 'cgu', to: 'pages#cgu', as: 'cgu'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :categories, through: :products

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :photo
  has_many :products, dependent: :destroy
  has_many :brands, -> { distinct.order(:id) }, through: :products

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
  belongs_to :category
  belongs_to :brand

  has_many :quote_items, dependent: :destroy
  has_many :quotes, through: :quote_items

  def self.ransackable_associations(auth_object = nil)
    %w[brand category]
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end

  def self.ransackable_scopes(auth_object = nil)
    %w[search_by_category_name]
  end

  def self.search_by_category_name(query)
    joins(:category).where("categories.name ILIKE ?", "%#{query}%")
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :quote_items, dependent: :destroy
  has_many :products, through: :quote_items

  validates :phone, format: { with: /\A0[1-9]\d{8}\z/ , message: ": Le numéro de téléphone doit être français et valide, composé uniquement de  10 chiffres" }
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\.[^@\s]+\z/, message: "doit être de type exemple@email.fr" }


end

app/models/quote_item.rb
class QuoteItem < ApplicationRecord
  belongs_to :quote
  belongs_to :product

  validates :product_id, uniqueness: { scope: :quote_id,
    message: "ne peut être ajouté plusieurs fois au même devis" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :search
  before_action :initialize_quote
  before_action :initialize_db

  private

  def initialize_db
    @products = Product.includes(:category, :brand)
    @categories = Category.all
    @brands = Brand.all
  end

  def initialize_quote
    return if session[:quote_id].present?
    @quote = Quote.find_or_create_by(id: session[:quote_id])
    session[:quote_id] = @quote.id
    @quote_items = @quote.quote_items
  end

  def search
    @q = Product.ransack(params[:q])
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
    @products = @brand.products
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save!
      redirect_to brand_path(@brand)
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    @brand.update(brand_params)
    if @brand.save
      redirect_to brand_path(@brand)
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    redirect_to brands_path
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @brands = @category.brands
    @products = @category.products
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save!
      redirect_to category_path(@category)
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    if @category.save
      redirect_to category_path(@category)
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :photo)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def infos
  end

  def legal
  end

  def policy
  end

  def cgu
  end

  def redirect
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_or_create_quote, only: [:show]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @products = if params[:q].present?
                  @q.result(distinct: true)

                else
                  Product.all.with_attached_photo
                end
  end

  def show
    @product = Product.find(params[:id])
    @quote_item = QuoteItem.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save!
      redirect_to product_path(@product)
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    if @product.save
      redirect_to product_path(@product)
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def set_or_create_quote
    @quote = Quote.find_by(id: session[:quote_id]) || Quote.create!
    session[:quote_id] = @quote.id
  end

  def product_params
    params.require(:product).permit(:name, :box, :link, :photo, :category_id, :brand_id)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_or_create_quote, only: [:show, :edit, :update, :send_my_quote]

  def show
    @quote_items = @quote.quote_items.includes(product: [:category, :brand]).sort_by { |item|
      [item.product.category.name, item.product.brand.name]
    }
    @products = @quote.products
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      redirect_to quote_path
    else
      render :edit
    end
  end

  def send_my_quote
    QuotesMailer.send_quote(@quote).deliver_now!
    QuotesMailer.send_for_asker(@quote).deliver_now!
    redirect_to redirect_path
    new_quote = Quote.create!
    session[:quote_id] = new_quote.id
  end

  private

  def set_or_create_quote
    @quote = Quote.find_by(id: session[:quote_id]) || Quote.create!
    session[:quote_id] = @quote.id
  end

  def quote_params
    params.require(:quote).permit(:first_name, :last_name, :phone, :email, :address, :company)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/quote_items_helper.rb
module QuoteItemsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_footer.html.erb
<section id="footer" class="border-top mt-5 py-5">
  <div class="container">
    <div class="row gy-5">
      <div class="col-12 col-md-4">
        <h4 class="text-center text-secondary">
          Retrouvez Nous
        </h4>

        <ul class="list-group">
          <li class="list-group-item border-0">Lundi 08:00–12:00, 14:00–18:00</li>
          <li class="list-group-item border-0">Mardi 08:00–12:00, 14:00–18:00</li>
          <li class="list-group-item border-0">Mercredi 08:00–12:00, 14:00–18:00</li>
          <li class="list-group-item border-0">Jeudi 08:00–12:00, 14:00–18:00</li>
          <li class="list-group-item border-0">Vendredi 08:00–12:00, 14:00–18:00</li>
          <li class="list-group-item border-0">Samedi 08:00–12:00, 14:00–19:00</li>
          <li class="list-group-item border-0">Dimanche Fermé</li>
        </ul>

      </div>

      <div class="col-12 col-md-4">
        <h4 class="text-center text-secondary">Informations</h4>
          <ul class="list-group">
            <li class="list-group-item border-0">
              <%= link_to 'Mentions Légales', legal_path, class:"text-black text-decoration-none" %>
            </li>
            <li class="list-group-item border-0">
              <%= link_to 'Politique de Confidentialité', policy_path, class:"text-black text-decoration-none" %>
            </li>
            <li class="list-group-item border-0">
              <%= link_to 'Conditions Générales d\'utilisation', cgu_path, class:"text-black text-decoration-none" %>
            </li>
          </ul>

      </div>

      <div class="col-12 col-md-4">
        <h4 class="text-center text-secondary">Makhfood Market</h4>

        <ul class="list-group">
          <li class="list-group-item border-0"><i class="bi bi-basket3-fill"></i> Grossiste alimentation et boisson pour particuliers et professionnels</li>
          <li class="list-group-item border-0"><i class="bi bi-clock-fill"></i> Ouvert du Lundi au samedi</li>

          <li class="list-group-item border-0">
            <%= link_to "https://www.google.fr/maps/place/39+Rue+des+Pays+Bas,+84100+Orange/@44.1257522,4.837311,17z/data=!3m1!4b1!4m6!3m5!1s0x12b590ed3bf56cd1:0xd3fa4c732302d6c5!8m2!3d44.1257484!4d4.8398913!16s%2Fg%2F11c4vfw3vz?entry=ttu", target: "_blank", class: "text-decoration-none text-dark" do %>
              <i class="bi bi-geo-alt-fill"></i> 39 Rue des Pays Bas, 84100 Orange
            <% end %>
          </li>

          <li class="list-group-item border-0">
            <%= link_to "tel:+33618045086", target: "_blank", class: "text-decoration-none text-dark" do %>
              <i class="bi bi-telephone-fill"></i> 06 18 04 50 86
            <% end %>
          </li>

          <li class="list-group-item border-0">
            <%= link_to "mailto:contact@makhfoodmarket.fr", target: "_blank", class: "text-decoration-none text-dark" do %>
              <i class="bi bi-envelope-fill"></i> contact@makhfoodmarket.fr
            <% end %>
          </li>



        </ul>
        <div class="mx-auto w-50">
          <%= image_tag 'makhfood_no_bg.png', class:"img-fluid" %>
        </div>
      </div>

    </div>
  </div>

<p class="text-end fw-light fst-italic mx-3 mt-5" style="font-size:10px;">
  <%= link_to 'Makhfood Market', root_path, class: "text-decoration-none text-black" %>, 2023
  Tous droits réservés ©.
  Propulsé par #1344.

</p>
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar border-bottom bg-white sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class:"text-decoration-none text-black grow-hover" do %>
      <%= image_tag 'makhfood_no_bg.png', width:"80" %>
      <span class="fw-medium d-none d-sm-inline">MAKHFOOD MARKET</span>
    <% end %>
    <%= render 'pages/nav-home' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon border-danger"></span>
    </button>
    <div class="offcanvas offcanvas-end bg-danger" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title mx-auto text-bg-danger" id="offcanvasDarkNavbarLabel">MAKHFOOD MARKET</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">

        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to 'ACCUEIL', root_path, class: 'nav-link text-bg-danger' %>
          </li>
          <li class="nav-item">
            <%= link_to 'GERER MON DEVIS', quote_path, class: 'nav-link text-bg-danger' %>
          </li>

        </ul>

        <%= search_form_for @q, class: "d-flex mt-5" do |f| %>
          <%= f.label :name_or_category_name_cont, hidden: true %>
          <%= f.search_field :name_or_category_name_cont, class: "form-control me-2", placeholder: "Chercher un produit" %>
          <%= f.submit "🔎", class: "btn btn-success" %>
        <% end %>

        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to 'TOUS NOS PRODUITS', products_path, class: "nav-link text-bg-danger" %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-bg-danger" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              NOS CATEGORIES
            </a>

            <ul class="dropdown-menu dropdown-menu bg-danger-subtle">
              <li><%= link_to 'Toutes les catégories', categories_path, class: "dropdown-item" %></li>

              <li>
                <hr class="dropdown-divider">
              </li>
              <% @categories.order(:name).each do |cat| %>
                <li><%= link_to cat.name, category_path(cat), class: "dropdown-item" %></li>
              <% end %>

            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-bg-danger" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              NOS MARQUES
            </a>

            <ul class="dropdown-menu bg-danger-subtle">
              <li><%= link_to 'Toutes les marques', brands_path, class: "dropdown-item" %></li>

              <li>
                <hr class="dropdown-divider">
              </li>
              <% @brands.order(:name).each do |b| %>
                <li>
                  <%= link_to b.name, brand_path(b), class: "dropdown-item" %>
                </li>
              <% end %>

            </ul>
          </li>
        </ul>

        <section class="text-bg-danger row fw-bold text-center gy-2 align-items-end align-items-center my-3">
          <div class="col-12">
            <i class="bi bi-basket3-fill"></i> Grossiste alimentation et boisson pour particuliers et professionnels
          </div>
          <div class="col-12">
            <i class="bi bi-clock-fill"></i> Ouvert du Lundi au samedi
          </div>
          <div class="col-12">
            <%= link_to "https://www.google.fr/maps/place/39+Rue+des+Pays+Bas,+84100+Orange/@44.1257522,4.837311,17z/data=!3m1!4b1!4m6!3m5!1s0x12b590ed3bf56cd1:0xd3fa4c732302d6c5!8m2!3d44.1257484!4d4.8398913!16s%2Fg%2F11c4vfw3vz?entry=ttu", target: "_blank", class: "text-decoration-none text-white" do %>
              <i class="bi bi-geo-alt-fill"></i> 39 Rue des Pays Bas, 84100 Orange
            <% end %>
          </div>
          <div class="col-12">
            <%= link_to "tel:+33618045086", target: "_blank", class: "text-decoration-none text-white" do %>
              <i class="bi bi-telephone-fill"></i> 06 18 04 50 86
            <% end %>
          </div>
          <div class="col-12">
            <%= link_to "mailto:contact@makhfoodmarket.fr", target: "_blank", class: "text-decoration-none text-white" do %>
              <i class="bi bi-envelope-fill"></i> contact@makhfoodmarket.fr
            <% end %>
          </div>
        </section>

        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to 'Mentions Légales', legal_path, class: 'nav-link text-bg-danger' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Politique de Confidentialité', policy_path, class: 'nav-link text-bg-danger' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Conditions Générales d\'utilisation', cgu_path, class: 'nav-link text-bg-danger' %>
          </li>

        </ul>



      </div>
    </div>
  </div>
</nav>

<style>
  .grow-hover {
    transition: transform 0.3s ease;
  }

  .grow-hover:hover {
    transform: scale(1.05)
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MAKHFOOD MARKET - Grossiste Alimentaire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/components/banner' %>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/components/admin' %>
    <%= render 'layouts/components/buttons-admin' if current_admin %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/components/_admin.html.erb
<section id="admin">
  <%= link_to 'Déconnexion de l\'admin', destroy_admin_session_path, data: {turbo_method: :delete} if current_admin %>
</section>

app/views/layouts/components/_banner.html.erb
<section id="info-bar" class="text-bg-danger row fw-bold text-center gx-0 align-items-center">
    <div class="col-12 col-md-3">
      <i class="bi bi-basket3-fill"></i> Grossiste alimentation et boisson pour particuliers et professionnels
    </div>
    <div class="col-12 col-md-2">
      <i class="bi bi-clock-fill"></i> Ouvert du Lundi au samedi
    </div>

    <div class="col-12 col-md-3">
      <%= link_to "https://www.google.fr/maps/place/39+Rue+des+Pays+Bas,+84100+Orange/@44.1257522,4.837311,17z/data=!3m1!4b1!4m6!3m5!1s0x12b590ed3bf56cd1:0xd3fa4c732302d6c5!8m2!3d44.1257484!4d4.8398913!16s%2Fg%2F11c4vfw3vz?entry=ttu", target: "_blank", class: "text-decoration-none text-white" do %>
        <i class="bi bi-geo-alt-fill"></i> 39 Rue des Pays Bas, 84100 Orange
      <% end %>
    </div>

    <div class="col-12 col-md-2">
      <%= link_to "tel:+33618045086", target: "_blank", class: "text-decoration-none text-white" do %>
        <i class="bi bi-telephone-fill"></i> 06 18 04 50 86
      <% end %>
    </div>

    <div class="col-12 col-md-2">
      <%= link_to "mailto:contact@makhfoodmarket.fr", target: "_blank", class: "text-decoration-none text-white" do %>
        <i class="bi bi-envelope-fill"></i> contact@makhfoodmarket.fr
      <% end %>
    </div>

</section>

app/views/layouts/components/_buttons-admin.html.erb
<div class="row my-5 text-center">
  <div class="col-12 col-md-4 my-3">
    <%= link_to 'Ajouter un Produit', new_product_path %>
  </div>

  <div class="col-12 col-md-4 my-3">
    <%= link_to 'Ajouter une Marque', new_brand_path %>
  </div>

  <div class="col-12 col-md-4 my-3">
    <%= link_to 'Ajouter une Catégorie', new_category_path %>
  </div>

</div>

app/views/layouts/components/_infos-makhfood.html.erb
<section class="container my-4">
  <h2 class="text-center my-3">Makhfood Market</h2>
  <div class="row">
    <div class="col-md-6">
      <label for="adress" class="form-label">Adresse :</label>
      <p class="form-control-plaintext">39 Rue des Pays Bas, 84100 Orange</p>
    </div>
    <div class="col-md-6">
      <label for="hours" class="form-label">Horaires:</label>
      <ul class="list-group">
        <li class="list-group-item">Lundi 08:00–12:00, 14:00–18:00</li>
        <li class="list-group-item">Mardi 08:00–12:00, 14:00–18:00</li>
        <li class="list-group-item">Mercredi 08:00–12:00, 14:00–18:00</li>
        <li class="list-group-item">Jeudi 08:00–12:00, 14:00–18:00</li>
        <li class="list-group-item">Vendredi 08:00–12:00, 14:00–18:00</li>
        <li class="list-group-item">Samedi 08:00–12:00, 14:00–19:00</li>
        <li class="list-group-item">Dimanche Fermé</li>
      </ul>
    </div>
  </div>
</section>

app/views/layouts/index/_all.html.erb
<div class="row w-100 justify-content-center">

  <div class="col-3 d-none d-lg-block sticky-top">
    <%= render 'layouts/index/filter', q: q, categories: categories, brands: brands %>
  </div>

  <div class="col-8 text-center">
   <%= render 'layouts/index/products', products: products %>
  </div>

</div>

app/views/layouts/index/_filter.html.erb
<section class="position-sticky start-0 top-50 p-1 translate-middle-y" style="z-index: 1;">

  <ul class="list-group">

    <% # Recherche %>

    <li class="list-group-item list-group-item-action list-group-item-danger">
      <%= search_form_for q, class: "d-flex" do |f| %>
        <%= f.label :name_or_category_name_cont, hidden: true %>
        <%= f.search_field :name_or_category_name_cont, class: "form-control me-2", placeholder: "Chercher un produit" %>
        <%= f.submit "🔎", class: "btn btn-success" %>
      <% end %>
    </li>

    <% # Produits %>

    <%= link_to products_path, class: "text-decoration-none text-dark" do %>
      <li class="list-group-item list-group-item-action list-group-item-danger">
        Tous les Produits
      </li>
    <% end %>

    <% # Catégories %>

    <a class="text-decoration-none text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapsing-1" aria-expanded="false" aria-controls="collapsing-1">
      <li class="list-group-item list-group-item-action list-group-item-danger">
      Catégories
      </li>
    </a>

    <ul class="collapse list-group" id="collapsing-1">

      <% categories.order(:name).each do |cat| %>
        <%= link_to category_path(cat), class: "text-decoration-none text-dark" do %>
          <li class="list-group-item list-group-item-action list-group-item-warning">
            <%= cat.name %>
          </li>
        <% end %>
      <% end %>

    </ul>

    </li>

      <% # Marques %>
      <a class="text-decoration-none text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapsing-2" aria-expanded="false" aria-controls="collapsing-2">
        <li class="list-group-item list-group-item-action list-group-item-danger rounded-bottom">
        Marques
        </li>
      </a>

      <ul id="collapsing-2" class="accordion-collapse collapse overflow-y-scroll list-group list-group-flush" style="max-height: 25vh; overflow-y: auto;">
        <% brands.order(:name).each do |b| %>
          <%= link_to brand_path(b), class: "text-decoration-none text-dark" do %>
            <li class="list-group-item list-group-item-action list-group-item-warning">
              <%= b.name %>
            </li>
          <% end %>
        <% end %>
      </ul>

  </ul>



</section>

app/views/layouts/index/_products.html.erb
<span class="text-secondary"><%= products.length %> produits</span>
<section class="row row-cols-lg-3 row-cols-md-2 row-cols-1 gx-1 gy-5">

  <% products.each_with_index do |product, i| %>

    <div class="col p-3 hover-card" id="product_<%= product.id %>"%>
      <%= link_to product_path(product), class: "text-decoration-none text-dark" do %>

        <div class="square-image-container">
          <%= cl_image_tag product.photo.key, class: 'w-100' %>
        </div>

        <p class="px-5">
          <%= product.name %>
        </p>

      <% end %>
      <%# <%= link_to 'supprimer', product_path(product), class: 'btn btn-danger', data: {turbo_method: :delete} %>
    </div>
  <% end %>

</section>


<style>

  .hover-card {
    transition: transform 0.3s ease;
  }
  .hover-card:hover {
    transform: scale(1.1);
  }
</style>

app/views/pages/_categories.html.erb
<h2 class="mt-5 mb-3 text-danger">
  CONSULTER NOS PRODUITS PAR CATEGORIE
</h2>

<section class="row g-1">

  <!-- Première colonne plus grande -->
  <div class="col-md-2 col-6">
    <%= link_to products_path, class: "text-decoration-none card" do %>
        <%= image_tag 'tous_les_produits.png', class: "object-fit-cover img-card-top rounded-top-1" %>
    <div class="card-body bg-danger rounded-bottom-1">
      <p class="card-text text-center text-white">
        TOUS NOS PRODUITS
      </p>
    </div>
    <% end %>
  </div>

  <% categories.each do |cat| %>
  <div class="col-md-2 col-6">
    <%= link_to category_path(cat), class: "text-decoration-none card" do %>
      <%= cl_image_tag( cat.photo.key, :transformation=>["square"], class: 'rounded-top-1' ) %>
      <div class="card-body bg-warning rounded-bottom-1">
        <p class="card-text text-center text-white">
          <%= cat.name %>
        </p>
      </div>
    <% end %>
  </div>
  <% end %>

</section>

app/views/pages/_nav-home.html.erb
<div class="d-flex">
  <%= link_to 'NOTRE CATALOGUE', products_path, class: "btn btn-danger" %>
  <%= search_form_for @q, class: "ms-3 d-none d-md-flex" do |f| %>
    <%= f.label :name_or_category_name_cont, hidden: true %>
    <%= f.search_field :name_or_category_name_cont, class: "form-control me-2", placeholder: "Chercher un produit" %>
    <%= f.submit "🔎", class: "btn btn-danger" %>
  <% end %>
</div>

<%= link_to 'DEMANDER MON DEVIS', quote_path, class: 'btn btn-secondary d-none d-lg-inline' %>

app/views/pages/home.html.erb
<main class="container">
  <section class="row my-5 p-3 justify-content-center">
    <div class="col-md-6 col-12">
      <%= image_tag 'entrepot.jpg', class: 'img-fluid rounded-2' %>
    </div>

    <div class="col-md-6 col-12 text-center my-3 ">
      <%= image_tag 'makhfood_no_bg.png', class: "w-50" %>
    </div>
  </section>

<div class="row">
  <p class="text-center text-danger fw-medium col-md-4 col-12">
    VOTRE SPECIALISTE GROSSISTE ALIMENTAIRE
  </p>
  <p class="text-center text-danger fw-medium col-md-4 col-12">
    OUVERT AUX PARTICULIERS ET PROFESSIONNELS
  </p>
  <p class="text-center text-danger fw-medium col-md-4 col-12">
    LIVRAISON DANS TOUTE LA FRANCE
  </p>
</div>

  <%= render 'pages/who' %>
  <%= render 'pages/now' %>
  <%= render 'pages/categories', categories: @categories %>

</main>

app/views/pages/infos.html.erb
<h1>Informations</h1>
<div>
  Carte
</div>
<div>
  Contact
</div>
div